PAF update
andrei1058/docs pull request #49
Opened 2022-12-07 18:26 UTC by rafi67000

PartyAndFriends hook update:

- API now support also NonExtended version (only mysql-bridge)
- RedisServer is no longer needed (You can use mysql database)

2023-01-22 23:42 UTC, JT122406 approved these changes

2023-01-24 19:40 UTC, andrei1058 commented
there are conflicts

2023-01-24 19:43 UTC, andrei1058 commented
there are conflicts

2023-01-24 20:09 UTC, JT122406 requested changes
This was all handled by me in #53 and can be closed

2023-02-05 13:59 UTC, OPADILOP reviewed
No need anymore its already added to the wiki.

2023-02-05 15:12 UTC, closed without merging