Update addons.md
andrei1058/docs pull request #54
Opened 2023-01-25 18:12 UTC by NotLewUwU

Just a new line

2023-01-25 21:26 UTC, JT122406 approved these changes
@andrei1058 Should be good to merge right in

2023-02-05 13:58 UTC, OPADILOP requested changes
You should make the link a little bit shorter. Like - 
https://polymart.org/resource/bedwars1058-adventuremode.3296
This to - 
https://polymart.org/resource/3296/
This it should be good to go

2023-02-28 09:33 UTC, tomkeuper requested changes

2023-02-28 09:33 UTC, tomkeuper commented on docs/BedWars1058/addons.md
> +- [AdventureMode - Set your players gamemode to adventure in the waiting lobby.](https://polymart.org/resource/bedwars1058-adventuremode.3296) - by NotLew_x
Make this line shorter as suggested before after that it can be merged

2023-02-28 09:36 UTC, tomkeuper commented
I just found out that this change is also implented in #57
I will close this in favor of the previous change as it has more in one commit

2023-02-28 09:36 UTC, closed without merging