Added new plugins and removed a setup.
andrei1058/docs pull request #57
Opened 2023-02-10 10:33 UTC by OPADILOP

Removed StudioBeam Development's setup because it's no longer available. Added IamTheDefender's Cosmetics and Item Rotation plugin. Added NotLew_x's AdventureMode plugin. Added RRS's Discord Stats plugin. Added by in some lines.

2023-02-12 14:15 UTC, andrei1058 requested changes

2023-02-12 14:15 UTC, andrei1058 commented on docs/BedWars1058/addons.md
> +- [Spectator Options - Add useful settings for spectators!](https://polymart.org/resource/1916/) - by CubeCrafter72
This is no longer available..

2023-02-28 09:31 UTC, tomkeuper commented
Please resolve changes so it can be merged

2023-03-06 11:20 UTC, OPADILOP reviewed
done as you said

2023-03-11 15:23 UTC, andrei1058 commented
sorry but there's a new conflict :((

2023-03-11 16:59 UTC, OPADILOP commented
No problem fixing it
Now

2023-03-11 17:14 UTC, OPADILOP commented
I have fixed and removed the plugins which were added. Because as my rearrangement, the plugins were already added to the upwards.

2023-03-11 17:35 UTC, andrei1058 approved these changes

2023-03-11 17:35 UTC, merged